openSUSE/gitarro

lib/gitbot_backend.rb
@MalloZup - What do you think about this? Could this be causing that `changelog_test` is always executed?
=> Fix condition to use 'changelog_test' instance variable

doc/README.md, lib/git_op.rb, lib/gitbot_backend.rb, lib/opt_parser.rb, tests/acceptance_tests/prs_operations.rb, tests/unit_tests/t_git_operation.rb
HTTPS can be enabled by using the switch --https (otherwise the gitbot will use SSH as it does currently).
This is useful to avoid any SSH configuration when using GitBot with public projects.
=> Add https support for git operations

tests/spec/test_lib.rb
Offenses:
tests/spec/test_lib.rb:7:15: C: [Corrected] Freeze mutable objects assigned to constants.
GITARRO_BIN = '../../gitarro.rb'
^^^^^^^^^^^^^^^^^^
tests/spec/test_lib.rb:9:1: C: [Corrected] Extra blank line detected.
14 files inspected, 2 offenses detected, 2 offenses corrected
=> LINT: fixup rubocop checkstyle

lib/gitarro/git_op.rb
This PR should fix an issue happening when certain repository has failed to be cloned.
On these cases, the following runs of `gitarro` would produce the next traceback during execution:
```
[manager-prs-susemanager-unittests] $ /bin/sh -xe /tmp/jenkins4518559196771098257.sh
+ /home/jenkins/bin/gitbot/gitarro.rb -r SUSE/spacewalk -c susemanager_unittests -d 'python backend pgsql unit test' -t /home/jenkins/jenkins-build/workspace/manager-prs-susemanager-unittests/gitbot_susemanager_unittests/spacewalk/susemanager-utils/testing/automation/susemanager-unittest.sh -u https://ci.suse.de/job/manager-prs-susemanager-unittests/4876/ -f susemanager/ -g /home/jenkins/jenkins-build/workspace/manager-prs-susemanager-unittests/gitbot_susemanager_unittests …
```
=> Fix: Check repository dir apart from the base git dir

tests/spec/cmdline_spec.rb
Raise an error if user don't use forked repo.
Usinng upstream repo can cause many problems and spamming
=> Don't allow defaults for rspec testing

gitarro.rb, lib/gitarro/backend.rb, tests/spec/cmdline_spec.rb, tests/spec/test_lib.rb, tests/unit_tests/t_backend.rb
Print a boolean variable to show if gitarro found opened PRs or not:
```
[PRS=FALSE] No Pull Requests opened or with changes newer than 60 seconds
```
```
[PRS=FALSE] No Pull Requests opened
```
```
[PRS=TRUE] Pull Requests opened. Analyzing them...
```
- https://github.com/openSUSE/gitarro/issues/71 (does NOT fix it completely, we still need to verify if there are some cases when we exit with != 0 when there are no errors)
Yes. Rspec.
Followed
=> Print a boolean variable to show if gitarro found opened PRs or not

lib/gitarro/backend.rb, tests/spec/cmdline_spec.rb, tests/spec/test_lib.rb
Do not exit 1 when --check is enabled, but show a message.
- https://github.com/openSUSE/gitarro/issues/71
Yes, two now rspec.
Followed
=> Do not exit 1 when --check is enabled, but show a message

doc/BASICS.md, gem/gitarro.gemspec, gitarro.rb, lib/gitarro/backend.rb, lib/gitarro/opt_parser.rb, tests/spec/secondary_spec.rb, tests/spec/test_lib.rb, tools/scripts/README.md, tools/scripts/changelog_test.rb
remove changelog tests/checks from backend.
This pr will remove changelog  logic from backend.rb in order to isolate the test and allow refactoring.
fix #54 
once the test will be isolated, the script will be freezed.
=> Init changelog isolation tests.

Rakefile, gitarro.rb, lib/gitarro/backend.rb, lib/gitarro/git_op.rb, lib/gitarro/opt_parser.rb, tests/spec/rspec_helper.rb, tests/spec/test_lib.rb, tools/scripts/changelog_test.rb
Fix guard clause syntax, as new rubocop version at Travis is complaining about the lack of empty lines after them:
```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/gitarro/backend.rb:320:5: C: Layout/EmptyLineAfterGuardClause: Add empty line after guard clause.
return false unless retriggered_by_comment?(pr.number, @context)
```
- https://github.com/openSUSE/gitarro/pull/121#issuecomment-424445954
No, just syntax fixing, adding empty lines.
=> Fix guard clause syntax

lib/gitarro/backend.rb
Return 1 in all cases where a test is failed, and not only for `retrigger_check()` as it was the case before.
- https://github.com/openSUSE/gitarro/issues/116
=> Always return != 0 when a test is not a success

gem/gitarro.gemspec
Push the version to 0.1.79 as 0.1.78 was already released to rubygems.org.
=> Version 0.1.79

gem/gitarro.gemspec, lib/gitarro/backend.rb
Fix triggered_by_pr_number and push version to 0.1.81.
`pr` variable do not exist at `triggered_by_pr_number`
=> Fix triggered_by_pr_number and push version to 0.1.81

lib/gitarro/backend.rb
Refactor launch_test_and_setup_status function. Instead of exiting where this function was called, the exit method is now inside it.
- https://github.com/openSUSE/gitarro/issues/139
No, just syntax fixing.
=> Exit directly in function definition

.rubocop_todo.yml, README.md, doc/ADVANCED.md, gem/gitarro.gemspec, lib/gitarro/backend.rb, tests/spec/secondary2_spec.rb, tests/spec/test_lib.rb, tools/scripts/changelog_test.rb
Related to Task: https://github.com/SUSE/spacewalk/issues/6346
It changes the way we re-run tests and we specify if changelog must be checked. we will use the checkboxes you see bellow: 
In the first case, gitarro will change from checked to unchecked after re-run th test.
=> [6346] Allow skipping changelog test from description

README.md, gem/gitarro.gemspec, lib/gitarro/backend.rb
Hotfix a mistake in params on retriggered_by_comment method.
As we added that method (to include both ways of trigger a test), The signature of the method was changed, so now we are passing the PR and we need then to specify the pr.number for issue_comments method.
```
def retrigger_needed?(pr)
return false unless retriggered_by_checkbox?(pr, @context) ||
retriggered_by_comment?(pr, @context)
```
=> Hotfix a mistake in params on retriggered_by_comment method

CHANGELOG.md, gem/gitarro.gemspec, gitarro.rb, lib/gitarro/backend.rb, tests/spec/secondary2_spec.rb, tools/scripts/changelog_test.rb
Fix the bug discussed here #166, where gitarro was adding a pending status on PR, when it runs with --check parameter.
In addition, when the test doesn't apply, we'll unmark the checkbox but we will include a comment to tell the user that this test was skipped.
A bit out of the scope, I also fixed something on gitarro.rb, so if we call the command with a -P parameter, we don't need to checkout all the PRs from github and jump in an iterator, as we can just checkout directly the PR passed by param.
I changed version, to save a commit, let me know if you prefer in a different commit.
- https://github.com/openSUSE/gitarro/issues/166
I improved those related with rerun, so now it lets a cleaner environment
=> Fix pending status using check parameter and add a "skipping comment" in checkbox when the test doesn't apply

CHANGELOG.md, gem/gitarro.gemspec, gitarro.rb, lib/gitarro/backend.rb
In order to follow the same behavior that the magic comments are doing, we should uncheck the re-run checkbox even if we have --check parameter on gitarro command.
=> Uncheck re-run checbox even whith --check parameter, -P parameter now check the status and file filters

.rubocop_todo.yml, CHANGELOG.md, doc/BASICS.md, gem/gitarro.gemspec, gitarro.rb, lib/gitarro/backend.rb, lib/gitarro/opt_parser.rb, tests/spec/secondary2_spec.rb, tests/spec/test_lib.rb
* My last PR doesn't catch the case of re-run a tests, as we were running re-trigger by PR, exactly like unreviewed_pr method but without the iteration through all the PRs. For some reason, the unittests didn't catch it, I would need to improve them at some point...
What we need is to check exactly the same steps, but only for the specified PR, so:
- b.pr_equal_specific_branch?(pr)
- b.retrigger_check(pr)
- b.unreviewed_new_pr?(pr, comm_st)
- b.reviewed_pr?(comm_st, pr)
* Also, we change the main loop, so now we don't break the loop with first test passed on first PR pending, instead we iterate through all the known pending PRs and run the tests if possible.
* In the other hand, we found a corner case with contexts that you want to re-trigger but you don't want to have a comment or …
=> Refactoring the PR parameter

CHANGELOG.md, gem/gitarro.gemspec, lib/gitarro/backend.rb, tests/spec/test_lib.rb
This PR fix an error introduced in `retriggered_by_checkbox?` when we changed include by a regular expression.
=> Fix the regular expression for re-run tests

lib/gitarro/backend.rb
Don't rerun a test if it is in pending state
None
Nope
=> Stop the test if it already in pending state

lib/gitarro/backend.rb
in a non-forced run, if the status is defined it means it is either started (pending) or finished (success or failed). No need to check the state
=> Don't run the test if any state is defined

Gemfile, gem/gitarro.gemspec
Make the gem compatible with Ruby 2.5 again
None
No
=> Make the gem compatible with Ruby 2.5 again
