openSUSE/gitarro

gitbot.rb
lib/opt_parser.rb

Run a test if the changelog (.changes file) was updated.
This can be turned off, if a comment with the text
no changelog needed!
is present.

add changelog_test

---

doc/ADVANCED.md
lib/gitarro/backend.rb
tests/spec/cmdline_spec.rb

Just return directly without using a var

Refactoring some method

---

doc/REAL_EXAMPLES.md

Docker example not working, removing until we can have it ready

---

gitarro.rb
lib/gitarro/backend.rb
tests/unit_tests/t_backend.rb

fix #67 , and adress partially #66

 Remove jstatus class var

---

Rakefile
lib/gitarro/git_op.rb

FIx an issue before it becomes one 
No but https://github.com/openSUSE/gitarro/issues/76

BUGFIX: create a git dir unless it exist

---

lib/gitarro/backend.rb
tests/spec/cmdline_spec.rb

refactor and fix changelogtest and test

fix Changelog

---

.gitignore
Gemfile
doc/ADVANCED.md
doc/BASICS.md
gem/gitarro.gemspec
lib/gitarro/backend.rb
lib/gitarro/opt_parser.rb
tests/spec/cmdline_spec.rb
tests/spec/test_lib.rb
tests/unit_tests/t_git_operation.rb
tests/unit_tests/t_opt_parser.rb

Adding Http_faraday_cache pro file store
#51

Add faraday caching

---

gitarro.rb
lib/gitarro/backend.rb
lib/gitarro/opt_parser.rb

Refactoring methods using ?
fix #64

Use ? for function returning true or false

---

README.md
gem/gitarro.gemspec
lib/gitarro/backend.rb

Backend ref

---

tests/unit_tests/t_git_operation.rb

Fix #76
- https://github.com/openSUSE/gitarro/issues/<NUMBER>

Add unit_test for gitop

---

lib/gitarro/backend.rb

Add warning wenn cache is not generated

---

doc/ADVANCED.md
gem/gitarro.gemspec
lib/gitarro/backend.rb
tests/spec/cmdline_spec.rb
tests/spec/test_lib.rb

Pass PR infos to  env variable

---

tests/spec/cmdline_spec.rb
tests/spec/test_lib.rb

- https://github.com/openSUSE/gitarro/issues/<NUMBER>

Reduce complexity of rspec test

---

gem/gitarro.gemspec
gitarro.rb
lib/gitarro/backend.rb
lib/gitarro/opt_parser.rb

add 1st draft branch

---

gem/gitarro.gemspec

Push Gem version to Version 0.1.78

Version 0.1.78

---

lib/gitarro/backend.rb

Export variables in all cases, removed by mystake by one of the previous commits.
Fixes #126

Export variables in all cases

---

tools/scripts/changelog_test.rb

changelog_test: Show an error if the environment variables do not exist

changelog_test: Show an error if the environment variables do not exist

---

gem/gitarro.gemspec

Version 0.1.80
To be merged after #127 AND #129

Version 0.1.80

---

lib/gitarro/backend.rb

Fixes #140 - removes unneeded local variable
- https://github.com/openSUSE/gitarro/issues/140
I have not written tests for this trivial change, but can do so if needed.

Remove unused variable

---

doc/ADVANCED.md
doc/BASICS.md
doc/CONTRIBUTING.md
doc/RELEASING.md
doc/TESTS.md

Fixed typos and abbreviations. Looks more professional now :)

fixed documentation typos.

---

README.md
doc/ADVANCED.md
doc/BASICS.md
doc/CONTRIBUTING.md
doc/RELEASING.md
doc/TESTS.md

This PR improves overall documentation.
- applied prettier
- fixed logical and spelling issues
- https://github.com/openSUSE/gitarro/issues/144
Only Documentation is changed. No tests required.
- worked on documentation in a separate branch & then squashed all commits.

Improved Documentation (#144)

---

README.md

- https://github.com/openSUSE/gitarro/issues/<NUMBER>

fix command in doc

---

CHANGELOG.md
gem/gitarro.gemspec

New version 0.1.82

---

doc/RELEASING.md

Improve releasing doc:
1. Mention that we need to release at GitHub as well.
2. Always submit the gem from a git tag, so we are sure we have a GitHub release.
3. General cleanup.

Improve releasing doc

---

lib/gitarro/backend.rb
tools/scripts/changelog_test.rb

Accept X or x for PR checkboxes, extra whitespaces, and be case-insensitive

Accept X or x for PR checkboxes, extra whitespaces, and be case-insensitive

---

tools/scripts/changelog_test.rb

Fix changelog script, magic checkbox

---

lib/gitarro/backend.rb

- https://github.com/openSUSE/gitarro/issues/<NUMBER>

PR body may be empty
